apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-argo
  name: test-argo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-argo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-argo
    spec:
      containers:
      - image: anantdockernew/testrepo
        name: my-image
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test-argo
